export const OPEN_FLASH_MESSAGE = 'OPEN_FLASH_MESSAGE';
export const CLOSE_FLASH_MESSAGE = 'CLOSE_FLASH_MESSAGE';
export const SET_PRODUCTS_GLOBAL_STATE = 'SET_PRODUCTS_GLOBAL_STATE'
export const SET_CATEGORIES_GLOBAL_STATE = 'SET_CATEGORIES_GLOBAL_STATE'